# Generated by Django 5.2.4 on 2025-08-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_dls", "0003_user_date_joined_user_verified_email_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
