# Generated by Django 5.2.4 on 2025-09-14 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_category_alter_material_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.category",
            ),
        ),
    ]
